//
//  AutomationAuthorization.swift
//  Ice
//
//  The consent gate for INSTALLING an automation (fire.10 P1).
//
//  Distinct from MCPWriteAuthorization (which approves a single direct move and
//  may carry a 5-minute lease). Installing a trigger mints a PERSISTENT
//  capability, so it gets its own prompt with no lease and no "Allow for 5
//  Minutes". The prompt text is generated by Fire from the canonical model —
//  never supplied by the agent — and approval binds to the exact write set via
//  a sealed grant.
//

import AppKit
import OSLog

@MainActor
final class AutomationAuthorization {
    static let shared = AutomationAuthorization()

    private let logger = Logger(category: "AutomationAuthorization")

    private init() {}

    struct Decision {
        let grant: SealedGrant
        let enable: Bool
    }

    /// Presents a Fire-generated install prompt for `rule`. Returns the sealed
    /// grant + whether to enable it, or nil if the user denied or sealing
    /// failed. The grant binds to the rule's exact condition, action, write
    /// set, and generation.
    func authorizeInstall(rule: TriggerRule) -> Decision? {
        let digest = TriggerCanonicalizer.digest(condition: rule.condition, action: rule.onEnter)
        let writeSet = rule.onEnter.writeSet

        NSApp.activate(ignoringOtherApps: true)

        let alert = NSAlert()
        alert.alertStyle = .informational
        alert.messageText = "Install menu-bar automation?"
        alert.informativeText = """
        \(rule.name)

        When \(Self.describe(rule.condition)), Fire will \(Self.describe(writeSet)).

        This automation can then run without asking again. Any change to its \
        condition, items, or destination requires your approval again.
        """
        // Deny is added first → default button (Return/Esc deny) — safe.
        alert.addButton(withTitle: "Deny")                // .alertFirstButtonReturn
        alert.addButton(withTitle: "Install Disabled")     // .alertSecondButtonReturn
        alert.addButton(withTitle: "Install and Enable")   // .alertThirdButtonReturn

        let enable: Bool
        switch alert.runModal() {
        case .alertSecondButtonReturn:
            enable = false
        case .alertThirdButtonReturn:
            enable = true
        default:
            logger.log("Automation install denied for \(rule.id, privacy: .public)")
            return nil
        }

        let version = (Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String) ?? "unknown"
        let grant = ApprovedAutomationGrant(
            triggerID: rule.id,
            generation: rule.generation,
            canonicalDigest: digest,
            allowedWriteSet: writeSet,
            approvedAt: Date(),
            approvedByFireVersion: version
        )
        guard let sealed = AutomationGrantStore.shared.seal(grant) else {
            logger.error("Failed to seal grant for \(rule.id, privacy: .public)")
            return nil
        }
        logger.log("Automation \(rule.id, privacy: .public) approved (enable=\(enable))")
        return Decision(grant: sealed, enable: enable)
    }

    /// Re-validates a trigger's grant immediately before an auto-fire (called by
    /// the engine / coordinator). Guards against a defaults-edited rule whose
    /// sealed grant no longer matches.
    func validateForFire(rule: TriggerRule, sealed: SealedGrant?) -> Bool {
        guard let sealed,
              sealed.grant.triggerID == rule.id,
              sealed.grant.generation == rule.generation,
              sealed.grant.canonicalDigest == TriggerCanonicalizer.digest(condition: rule.condition, action: rule.onEnter),
              AutomationGrantStore.shared.validates(sealed)
        else {
            return false
        }
        return true
    }

    // MARK: Fire-generated descriptions (never agent-supplied)

    private static func describe(_ condition: TriggerCondition) -> String {
        switch condition {
        case .appFocus(let bundleID, let state):
            return state == .active
                ? "“\(bundleID)” becomes the frontmost app"
                : "“\(bundleID)” stops being the frontmost app"
        case .batteryBelow(let percent, _):
            return "battery drops below \(percent)%"
        case .timeWindow(let days, let start, let end, _):
            let dayList = days.sorted { $0.rawValue < $1.rawValue }.map(Self.short).joined(separator: ", ")
            return String(
                format: "the time is %02d:%02d–%02d:%02d on %@",
                start.hour, start.minute, end.hour, end.minute,
                dayList.isEmpty ? "any day" : dayList
            )
        }
    }

    private static func describe(_ moves: [MovePlan]) -> String {
        guard !moves.isEmpty else { return "make no changes" }
        let grouped = Dictionary(grouping: moves, by: { $0.toSection })
        let parts = grouped.map { section, items -> String in
            let names = items.map { "“\($0.bundleID)”" }.joined(separator: ", ")
            return "move \(names) to \(Self.sectionName(section))"
        }
        return parts.sorted().joined(separator: "; ")
    }

    private static func sectionName(_ section: TriggerSection) -> String {
        switch section {
        case .alwaysVisible: return "the always-visible area"
        case .hidden:        return "the hidden section"
        case .alwaysHidden:  return "the always-hidden section"
        }
    }

    private static func short(_ weekday: Weekday) -> String {
        switch weekday {
        case .sunday: return "Sun"
        case .monday: return "Mon"
        case .tuesday: return "Tue"
        case .wednesday: return "Wed"
        case .thursday: return "Thu"
        case .friday: return "Fri"
        case .saturday: return "Sat"
        }
    }
}
