//
//  TriggerNarrator.swift
//  Ice
//
//  The single source of truth for how Fire describes an automation to the user
//  (fire.10 P1). These strings are SECURITY-RELEVANT: they are what the consent
//  prompt shows and what `list_triggers` reports back to the agent. They are
//  generated by Fire from its own canonical domain model — never supplied by
//  the agent — so an agent cannot make a dangerous automation read as benign.
//
//  Used by `AutomationAuthorization` (install/remove prompts) and
//  `TriggerSummary` construction (the agent-facing read view).
//

import Foundation

enum TriggerNarrator {
    /// A human sentence fragment for a condition, e.g.
    /// "“com.tinyspeck.slackmacgap” becomes the frontmost app".
    static func describe(_ condition: TriggerCondition) -> String {
        switch condition {
        case .appFocus(let bundleID, let state):
            return state == .active
                ? "“\(bundleID)” becomes the frontmost app"
                : "“\(bundleID)” stops being the frontmost app"
        case .batteryBelow(let percent, _):
            return "battery drops below \(percent)%"
        case .timeWindow(let days, let start, let end, _):
            let dayList = days.sorted { $0.rawValue < $1.rawValue }
                .map(Self.short).joined(separator: ", ")
            return String(
                format: "the time is %02d:%02d–%02d:%02d on %@",
                start.hour, start.minute, end.hour, end.minute,
                dayList.isEmpty ? "any day" : dayList
            )
        }
    }

    /// A human sentence fragment for a write set, e.g.
    /// "move “com.bitwarden.desktop” to the hidden section".
    static func describe(_ moves: [MovePlan]) -> String {
        guard !moves.isEmpty else { return "make no changes" }
        let grouped = Dictionary(grouping: moves, by: { $0.toSection })
        let parts = grouped.map { section, items -> String in
            let names = items.map { "“\($0.bundleID)”" }.joined(separator: ", ")
            return "move \(names) to \(Self.sectionName(section))"
        }
        return parts.sorted().joined(separator: "; ")
    }

    /// A human sentence fragment for a whole action.
    static func describe(_ action: TriggerAction) -> String {
        describe(action.writeSet)
    }

    static func sectionName(_ section: TriggerSection) -> String {
        switch section {
        case .alwaysVisible: return "the always-visible area"
        case .hidden:        return "the hidden section"
        case .alwaysHidden:  return "the always-hidden section"
        }
    }

    static func short(_ weekday: Weekday) -> String {
        switch weekday {
        case .sunday: return "Sun"
        case .monday: return "Mon"
        case .tuesday: return "Tue"
        case .wednesday: return "Wed"
        case .thursday: return "Thu"
        case .friday: return "Fri"
        case .saturday: return "Sat"
        }
    }
}
